### PR TITLE
Update for Rails 5 compatibility

### PR DESCRIPTION
**Pull request by jkowens**
Rack 2.0 changed the session store API. 

See: rack/rack@4224c02

### CODE REVIEW

**Comment by jkowens** [comment]
Not sure what's changed with reseting the session that it is not changing the session_id value 😖

**Comment by jkowens** [comment]
@JonathanTron any idea why some of the Travis jobs seem to randomly fail with errors like `FATAL: database "sequel_rails_test" does not exist`?

**Comment by ludalex** [comment]
When is this going to be merged? I've been using @jkowens fork with Rails 5 quite successfully.. only issue I have is SQL queries don't get logged in console. Have you noticed this too?

**Comment by jkowens** [comment]
@ludalex I created a quick Rails 5 demo app and I'm seeing SQL queries logged in the console.

**Comment by jkowens** [comment]
@ludalex I was just reviewing some commits and I came across this #109. It looks like logging depends on a method that was added to Sequel in version [4.35.0](https://github.com/jeremyevans/sequel/blob/master/CHANGELOG#L65). I'm wondering if maybe you have an older version?

**Comment by ludalex** [comment]
@jkowens nope, using `sequel (4.36.0)`. 
And this is how I use your fork/branch: `gem 'sequel-rails', :github => 'jkowens/sequel-rails', :branch => 'rails5'`. See some issues with it?
Also I didn't configure anything logging-relataed in my app, which is a fairly new one too, created with `rails new app --api --skip-active-record`

**Comment by jkowens** [comment]
@ludalex Is there any output in your development.log? Do you see SQL queries logged if you build `sequel-rails` from master?

`gem 'sequel-rails', :github => 'TalentBox/sequel-rails', :branch => 'master'`

**Comment by ludalex** [comment]
@jkowens queries in development.log are logged with both master and your branch.

I just set up a new rails5 project this time without the `--skip-active-record` flag and without removing lines that import `active_record` in `application.rb` queries get logged in console.
So i believe the not logging issue is due to something left out when creating a project skipping AR.

Also, I tried to manually remove AR from the rails5 test vanilla project and couldn't succeed due to `ActiveSupport` depending on it:

<details>
 <summary>Stack trace when booting with `require "active_record/railtie"` commented in `application.rb`</summary> 
 ```
/Users/ldx/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/railtie/configuration.rb:95:in `method_missing': undefined method `active_record' for #<Rails::Application::Configuration:0x007fe4e414d310> (NoMethodError)
 	from /Users/ldx/testttt2/config/initializers/new_framework_defaults.rb:12:in `<top (required)>'
 	from /Users/ldx/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:287:in `load'
 	from /Users/ldx/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:287:in `block in load'
 	from /Users/ldx/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:259:in `load_dependency'
 	from /Users/ldx/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:287:in `load'
 	from /Users/ldx/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/engine.rb:648:in `block in load_config_initializer'
 	from /Users/ldx/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/notifications.rb:166:in `instrument'
 	from /Users/ldx/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/engine.rb:647:in `load_config_initializer'
 	from /Users/ldx/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
 	from /Users/ldx/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/engine.rb:611:in `each'
 	from /Users/ldx/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/engine.rb:611:in `block in <class:Engine>'
 	from /Users/ldx/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/initializable.rb:30:in `instance_exec'
 	from /Users/ldx/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/initializable.rb:30:in `run'
 	from /Users/ldx/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/initializable.rb:55:in `block in run_initializers'
 	from /Users/ldx/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
 	from /Users/ldx/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
 	from /Users/ldx/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
 	from /Users/ldx/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
 	from /Users/ldx/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
 	from /Users/ldx/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/initializable.rb:44:in `each'
 	from /Users/ldx/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/initializable.rb:44:in `tsort_each_child'
 	from /Users/ldx/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:415:in `call'
 	from /Users/ldx/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:415:in `each_strongly_connected_component_from'
 	from /Users/ldx/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
 	from /Users/ldx/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each'
 	from /Users/ldx/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `call'
 	from /Users/ldx/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
 	from /Users/ldx/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
 	from /Users/ldx/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
 	from /Users/ldx/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/initializable.rb:54:in `run_initializers'
 	from /Users/ldx/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0/lib/rails/application.rb:352:in `initialize!'
 	from /Users/ldx/testttt2/config/environment.rb:5:in `<top (required)>'
```
</details>

**Comment by jkowens** [comment]
@ludalex you also need to comment out the following line in your `config/initializers/new_framework_defaults.rb`:

`#Rails.application.config.active_record.belongs_to_required_by_default = true`

**Comment by ludalex** [comment]
@jkowens you're correct, after doing that, it works fine - and it becomes exactly like a project created with `--skip-active-record` - and doesn't log queries in the console.

I think this is the issue: #113 - basically it stops logging when AR is removed.

**Comment by adamgotterer** [comment]
Any updates on this PR? Anything I can do to help get it moving again. Would love to see this get merged as it's something I need.

**Comment by jkowens** [comment]
@adamgotterer I think @JonathanTron or @JosephHalter just need to weigh in on the updates. The commits in this PR mostly just handle the changes for the Rack 2.0 session store. Hopefully they'll get merged in soon!

As far as the logging issue, it sounds like it needs a PR created to fix it. I didn't see the issue @ludalex described. @ludalex did the fix mentioned in #113 fix your issue?

**Comment by adamgotterer** [comment]
Is the rack 2.0 session store the only thing preventing `sequel-rails` from working with Rails 5?

**Comment by jkowens** [comment]
The specs turned green 😉  

I created a basic test app, and everything seemed to be working ok. If you have an existing app that you're upgrading to Rails 5 it would be interesting to hear your results.

**Comment by JonathanTron** [comment]
Thanks for your work, I'll be working today on releasing a new version.

**Comment by jkowens** [comment]
@JonathanTron Thanks!

**Pull request merged**
