### PR TITLE
feat: silence logger for sequel session store

### PR DESCRIPTION
**Pull request by mjc-gh**
This PR silences the logger when reading and writing sessions to the database. This mimics behavior found in the [ActiveRecord::SessionStore](https://github.com/rails/activerecord-session_store/blob/d7a918cc2b24b4261fead06538d7d8f8d8b2a1d1/lib/action_dispatch/session/active_record_store.rb#L69-L78) class.

Not sure how to best test this. Any suggestions?

### CODE REVIEW

**Comment by JonathanTron** [comment]
Hi @mjc-gh, thanks again for this new PR.

About testing it, you can probably do it in an integration test, changing the Sequel logger to output to a `StringIO` and adding your expectation on that after calling the code to exercise.

**Comment by mjc-gh** [comment]
@JonathanTron sounds good! I'll update this PR in the next day or two and get those specs in place. Thanks!

**Comment by gencer** [comment]
@JonathanTron, This should be merged because it exposes session data to the logs.

/cc @mjc-gh any update?

**Comment by JonathanTron** [comment]
Thanks @mjc-gh for the PR and @gencer for the push ;)

**Pull request merged**
